name: Build OpenVPN3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Set up dependencies
      run: |
        brew install asio cmake jsoncpp lz4 openssl pkg-config xxhash

    - name: Clone code
      run: |
        cd ~
        mkdir src
        cd src
        git clone https://github.com/misa198/openvpn3.git openvpn3

    - name: Build OpenVPN3
      run: |
        mkdir build-openvpn3
        cd build-openvpn3
        cmake -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl -DCMAKE_PREFIX_PATH=/opt/homebrew ~/src/openvpn3
        cmake --build .
        ls -la
        mkdir dist
        cp ./test/ovpncliagent ./dist
        cp ./test/ovpncli ./dist
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-openvpn3
        path: ./build-openvpn3/dist

